name: CI/CD preview

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master


jobs:
  build:
    name: Build & lint for preview
    runs-on: ubuntu-latest
    environment: vercel_deploy
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL}}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run test
        run: npm run test || echo "Aucun test"
  deploy-preview:
    name: Deploy project to Vercel for preview
    runs-on: ubuntu-latest
    needs: ["build"]
    environment: vercel_deploy
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL}}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Vercel Artifacts
        run: vercel build --target=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        run: vercel deploy --target=preview --prebuilt --token=${{ secrets.VERCEL_TOKEN }}